language: node_js
node_js:
  - "12"
cache: yarn
jobs:
  include:
    - stage: deploy to development
      if: branch = master
      install:
        - yarn install
        - yarn global add @angular/cli
      script: ng build --configuration=development
      deploy:
        skip_cleanup: true
        provider: script
        script: bash deploy.sh development $FIREBASE_TOKEN
        on:
          branch: master
    - stage: deploy to production
      if: tag =~ ^v
      install:
        - yarn install
        - yarn global add @angular/cli
      script: ng build --configuration=production
      deploy:
        skip_cleanup: true
        provider: script
        script: bash deploy.sh production $FIREBASE_TOKEN
        on:
          all_branches: true
