language: node_js
node_js:
  - "12"
cache: yarn
jobs:
  include:
    - stage: deploy to staging
      if: tag IS NOT present
      install:
        - yarn install
        - yarn global add @angular/cli
      script: ng build --configuration=staging
      deploy:
        skip_cleanup: true
        provider: firebase
        project: staging
        token:
          secure: $FIREBASE_TOKEN
      on:
        branch: master
    - stage: deploy to production
      if: tag IS present
      install:
        - yarn install
        - yarn global add @angular/cli
      script: ng build --configuration=production
      deploy:
        skip_cleanup: true
        provider: firebase
        project: production
        token:
          secure: $FIREBASE_TOKEN
      on:
        tags: true
        all_branches: true
