export class ApiNDP {
  static Notifications = 'notifications';
  static Demo = 'demo';
  static Projects = 'projects';
  static Sources = 'sources';
  static Teams = 'teams';
  static Users = 'users';
  static Lock = 'lock';
  static Me = 'me';
  static DailyReports = 'daily-reports';
  static Names = 'names';
  static Ratings = 'ratings';
  static Aggregate = 'aggregate';
  static Rating_Change_Aggregate = 'rating-change-aggregate';
  static New = 'new';
  static Contacts = 'contacts';
  static ContactSources = 'contact-sources';
  static ContactResults = 'contact-results';
  static TelesalesReports = 'telesales-aggregate';
  static Assignments = 'assignments';
}
